# Generated by Django 4.2.5 on 2024-03-15 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('focus_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detectionevent',
            name='session_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
