# Generated by Django 4.2.5 on 2024-03-22 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('focus_tracker', '0004_alter_session_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='detectionevent',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='detectionimages/'),
        ),
    ]
