# Generated by Django 5.0.3 on 2024-03-27 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('focus_tracker', '0005_detectionevent_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='EEGEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp_epoch', models.BigIntegerField(help_text='Epoch timestamp of the event')),
                ('timestamp_formatted', models.CharField(help_text='Formatted time as HH:MM:SS', max_length=8)),
                ('focus_pm', models.FloatField(help_text='Focus measurement')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
