# Generated by Django 4.2.5 on 2024-03-29 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('focus_tracker', '0005_detectionevent_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='detectionevent',
            name='frequency',
            field=models.IntegerField(default=0),
        ),
    ]
