# Generated by Django 5.0.3 on 2024-03-28 21:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("focus_tracker", "0005_detectionevent_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="detectionevent",
            name="aspect_ratio",
        ),
    ]
