# Generated by Django 5.0.3 on 2024-03-27 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('focus_tracker', '0006_eegevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eegevent',
            name='timestamp_epoch',
            field=models.FloatField(help_text='Epoch timestamp of the event'),
        ),
    ]
