# Generated by Django 4.2.5 on 2024-03-30 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('focus_tracker', '0006_detectionevent_frequency'),
        ('focus_tracker', '0007_alter_eegevent_timestamp_epoch'),
    ]

    operations = [
    ]
