# Generated by Django 4.2.5 on 2024-03-30 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('focus_tracker', '0008_merge_20240330_1552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detectionevent',
            name='frequency',
        ),
    ]
