# Generated by Django 4.2.5 on 2024-03-30 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('focus_tracker', '0009_remove_detectionevent_frequency'),
    ]

    operations = [
        migrations.AddField(
            model_name='detectionevent',
            name='frequency',
            field=models.IntegerField(default=0),
        ),
    ]
