# Generated by Django 5.0.3 on 2024-03-30 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('focus_tracker', '0010_detectionevent_frequency'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlowEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp_epoch', models.FloatField(help_text='Epoch timestamp of the event')),
                ('timestamp_formatted', models.CharField(help_text='Formatted time as HH:MM:SS', max_length=8)),
                ('flow', models.CharField(default='', help_text='Flow State (Not in Flow or Flow)', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
