# Generated by Django 5.0.3 on 2024-04-01 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('focus_tracker', '0011_flowevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='flowevent',
            name='flowCount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='flowevent',
            name='flowNotFlowRatio',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='flowevent',
            name='notInFlowCount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='flowevent',
            name='predictionSum',
            field=models.IntegerField(default=0),
        ),
    ]
