# Generated by Django 4.2.5 on 2024-04-18 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('focus_tracker', '0012_flowevent_flowcount_flowevent_flownotflowratio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionHistoryEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=255, null=True)),
                ('total_distractions', models.IntegerField(default=0)),
            ],
        ),
    ]
