# Generated by Django 4.2.5 on 2024-04-20 21:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('focus_tracker', '0013_sessionhistoryevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionhistoryevent',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
