# Generated by Django 5.0.3 on 2024-04-29 21:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("focus_tracker", "0014_sessionhistoryevent_timestamp"),
    ]

    operations = [
        migrations.CreateModel(
            name="FocusEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp_epoch",
                    models.FloatField(help_text="Epoch timestamp of the event"),
                ),
                (
                    "timestamp_formatted",
                    models.CharField(
                        help_text="Formatted time as HH:MM:SS", max_length=8
                    ),
                ),
                (
                    "focus",
                    models.CharField(
                        default="",
                        help_text="Focus State (Not in Focus or Focus)",
                        max_length=20,
                    ),
                ),
                ("focusCount", models.IntegerField(default=0)),
                ("notInFocusCount", models.IntegerField(default=0)),
                ("predictionSum", models.IntegerField(default=0)),
                ("FocusNotFocusRatio", models.FloatField(default=0.0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
