# Generated by Django 5.0.3 on 2024-04-30 00:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("focus_tracker", "0015_focusevent"),
    ]

    operations = [
        migrations.AddField(
            model_name="flowevent",
            name="session_id",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="focusevent",
            name="session_id",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
