# Generated by Django 5.0.3 on 2024-04-30 16:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("focus_tracker", "0016_flowevent_session_id_focusevent_session_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="SessionLength",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_id", models.CharField(max_length=255, null=True)),
                ("session_length", models.FloatField(default=0.0)),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
